[template]
name = "service-crate-template"
description = "生成 core、sdk 包"

[placeholders]
entity = { prompt = "实体名", type = "string", default = 'account' }
db_prefix = { prompt = "数据库表前缀", type = "string", default = "acc" }